{{- if semverCompare "<v1.25.0" .Capabilities.KubeVersion.Version }}
{{- if and .Values.rbacEnabled .Values.podSecurityPolicy.create }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Release.Name }}
  annotations:
   seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
   seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
spec:
  requiredDropCapabilities:
    - ALL
  privileged: false
  allowPrivilegeEscalation: false
  defaultAllowPrivilegeEscalation: false
  hostNetwork: false
  hostPID: false
  hostIPC: false
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  supplementalGroups:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  hostNetwork: false
  hostIPC: false
  hostPID: false
  volumes:
  - secret
  - configMap
  - emptyDir
  - projected
{{- end }}
{{- end }}
