{{- if .Values.backup.deploy}}
{{- if or (or (eq "all" .Values.global.deploymentType) (eq "internal" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sda.fullname" . }}-backup
  labels:
    role: backup
    app: {{ template "sda.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Release.Name }}-backup
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ default "3" .Values.global.revisionHistory }}
  selector:
    matchLabels:
      app: {{ template "sda.name" . }}-backup
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "sda.name" . }}-backup
        role: backup
        release: {{ .Release.Name }}
      annotations:
  {{- if not .Values.global.vaultSecrets }}
        checksum/config: {{ include (print $.Template.BasePath "/backup-secrets.yaml") . | sha256sum }}
  {{- end }}
  {{- if .Values.global.podAnnotations }}
{{- toYaml .Values.global.podAnnotations | nindent 8 -}}
  {{- end }}
  {{- if .Values.backup.annotations }}
{{- toYaml .Values.backup.annotations | nindent 8 -}}
  {{- end }}
    spec:
  {{- if .Values.global.rbacEnabled}}
      serviceAccountName: {{ .Release.Name }}
  {{- end }}
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
  {{- if .Values.global.pkiPermissions }}
      initContainers:
      - name: tls-init
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["/bin/cp /tls-certs/* /tls/ && chown 65534:65534 /tls/* && chmod 0600 /tls/*"]
        securityContext:
          allowPrivilegeEscalation: false
    {{- if .Values.global.extraSecurityContext }}
{{- toYaml .Values.global.extraSecurityContext | nindent 10 -}}
    {{- end }}
        volumeMounts:
        - name: tls-certs
          mountPath: /tls-certs
        - name: tls
          mountPath: /tls
  {{- end }}
      containers:
      - name: s3-backup
        image: "{{ .Values.backup.repository }}:{{ .Values.backup.imageTag }}"
        imagePullPolicy: {{ .Values.backup.imagePullPolicy | quote }}
        command: ["sda-sync"]
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: ARCHIVE_TYPE
  {{- if eq "s3" .Values.global.archive.storageType }}
          value: "s3"
        - name: ARCHIVE_URL
          value: {{ required "S3 archive URL missing" .Values.global.archive.s3Url }}
        - name: ARCHIVE_BUCKET
          value: {{ required "S3 archive bucket missing" .Values.global.archive.s3Bucket }}
        - name: ARCHIVE_REGION
          value: {{ default "us-east-1" .Values.global.archive.s3Region }}
        - name: ARCHIVE_CHUNKSIZE
          value: {{ .Values.global.archive.s3ChunkSize | quote }}
    {{- if .Values.global.archive.s3CaFile }}
        - name: ARCHIVE_CACERT
          value: {{ template "tlsPath" . }}/{{ .Values.global.archive.s3CaFile }}
    {{- end }}
  {{- else }}
          value: "posix"
        - name: ARCHIVE_LOCATION
          value: "{{ .Values.global.archive.volumePath }}"
  {{- end }}
        - name: BACKUP_TYPE
  {{- if eq "s3" .Values.global.backupArchive.storageType }}
          value: "s3"
        - name: BACKUP_URL
          value: {{ required "S3 backup archive URL missing" .Values.global.backupArchive.s3Url }}
        - name: BACKUP_BUCKET
          value: {{ required "S3 backup archive bucket missing" .Values.global.backupArchive.s3Bucket }}
        - name: BACKUP_REGION
          value: {{ default "us-east-1" .Values.global.backupArchive.s3Region }}
        - name: BACKUP_CHUNKSIZE
          value: {{ .Values.global.backupArchive.s3ChunkSize | quote }}
    {{- if .Values.global.backupArchive.s3CaFile }}
        - name: BACKUP_CACERT
          value: {{ template "tlsPath" . }}/{{ .Values.global.backupArchive.s3CaFile }}
    {{- end }}
  {{- else }}
          value: "posix"
        - name: BACKUP_LOCATION
          value: "{{ .Values.global.backupArchive.volumePath }}"
  {{- end }}
        - name: BROKER_DURABLE
          value: {{ .Values.global.broker.durable | quote }}
        - name: BROKER_EXCHANGE
          value: {{ default "sda" .Values.global.broker.exchange }}
        - name: BROKER_QUEUE
          value: {{ .Values.global.broker.backupRoutingKey }}
        - name: BROKER_HOST
          value: {{ required "A valid MQ host is required" .Values.global.broker.host | quote }}
        - name: BROKER_PORT
          value: {{ .Values.global.broker.port | quote }}
        - name: BROKER_ROUTINGERROR
          value: {{ .Values.global.broker.routingError }}
        - name: BROKER_ROUTINGKEY
          value: "completed"
        - name: BROKER_VHOST
          value: {{ .Values.global.broker.vhost | quote }}
        - name: BROKER_SERVERNAME
          value: {{ .Values.global.broker.host | quote }}
        - name: BROKER_SSL
          value: "true"
        - name: BROKER_VERIFYPEER
          value: {{ .Values.global.broker.verifyPeer | quote }}
  {{- if .Values.global.broker.ssl }}
        - name: BROKER_CACERT
          value: {{ include "tlsPath" . }}/ca.crt
    {{- if .Values.global.broker.verifyPeer }}
        - name: BROKER_CLIENTCERT
          value: {{ include "tlsPath" . }}/backup.crt
        - name: BROKER_CLIENTKEY
          value: {{ include "tlsPath" . }}/backup.key
    {{- end }}
  {{- end }}
  {{- if or (eq "verify-ca" .Values.global.db.sslMode) (eq "verify-full" .Values.global.db.sslMode) }}
        - name: DB_CACERT
          value: {{ include "tlsPath" . }}/ca.crt
  {{- end }}
  {{- if eq "verify-full" .Values.global.db.sslMode }}
        - name: DB_CLIENTCERT
          value: {{ include "tlsPath" . }}/backup.crt
        - name: DB_CLIENTKEY
          value: {{ include "tlsPath" . }}/backup.key
  {{- end }}
        - name: DB_DATABASE
          value: {{ default "lega" .Values.global.db.name | quote }}
        - name: DB_HOST
          value: {{ required "A valid DB host is required" .Values.global.db.host | quote }}
        - name: DB_PORT
          value: {{ .Values.global.db.port | quote }}
        - name: DB_SSLMODE
          value: {{ .Values.global.db.sslMode | quote }}
  {{- if .Values.global.logLevel }}
        - name: LOG_LEVEL
          value: {{ .Values.global.logLevel | quote }}
  {{- end }}
  {{- if not .Values.global.vaultSecrets }}
    {{- if eq "s3" .Values.global.archive.storageType }}
        - name: ARCHIVE_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-s3archive-keys
              key: s3ArchiveAccessKey
        - name: ARCHIVE_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-s3archive-keys
              key: s3ArchiveSecretKey
    {{- end }}
    {{- if eq "s3" .Values.global.backupArchive.storageType }}
        - name: BACKUP_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-s3backup-keys
              key: s3BackupAccessKey
        - name: BACKUP_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-s3backup-keys
              key: s3BackupSecretKey
    {{- end }}
        - name: BROKER_PASSWORD
          valueFrom:
              secretKeyRef:
                name: {{ template "sda.fullname" . }}-backup
                key: mqPassword
        - name: BROKER_USER
          valueFrom:
              secretKeyRef:
                name: {{ template "sda.fullname" . }}-backup
                key: mqUser
        - name: DB_PASSWORD
          valueFrom:
              secretKeyRef:
                name: {{ template "sda.fullname" . }}-backup
                key: dbPassword
        - name: DB_USER
          valueFrom:
              secretKeyRef:
                name: {{ template "sda.fullname" . }}-backup
                key: dbUser
  {{ else }}
        - name: CONFIGFILE
          value: {{ include "confFile" . }}
  {{- end }}
        resources:
{{ toYaml .Values.backup.resources | trim | indent 10 }}
        volumeMounts:
  {{- if eq "posix" .Values.global.archive.storageType }}
        - name: archive
          mountPath: {{ .Values.global.archive.volumePath | quote }}
  {{- end }}
  {{- if eq "posix" .Values.global.backupArchive.storageType }}
        - name: archive
          mountPath: {{ .Values.global.backupArchive.volumePath | quote }}
  {{- end }}
  {{- if not .Values.global.pkiService }}
        - name: tls
          mountPath: {{ template "tlsPath" . }}
  {{- end }}
      volumes:
  {{- if not .Values.global.pkiService }}
        - name: {{ ternary "tls" "tls-certs" (empty .Values.global.pkiPermissions) }}
          secret:
            defaultMode: 0440
            secretName: {{ template "sda.fullname" . }}-backup-certs
    {{- if .Values.global.pkiPermissions }}
        - name: tls
          emptyDir:
            medium: Memory
            sizeLimit: 10Mi
    {{- end }}
  {{- end }}
  {{- if eq "posix" .Values.global.archive.storageType }}
        - name: archive
    {{- if .Values.global.archive.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.global.archive.existingClaim }}
    {{- else }}
          nfs:
            server: {{ required "An archive NFS server is required" .Values.global.archive.nfsServer | quote }}
            path: {{ if .Values.global.archive.nfsPath }}{{ .Values.global.archive.nfsPath | quote }}{{ else }}{{ "/" }}{{ end }}
    {{- end }}
  {{- end }}
  {{- if eq "posix" .Values.global.backupArchive.storageType }}
        - name: backup
    {{- if .Values.global.backupArchive.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.global.backupArchive.existingClaim }}
    {{- else }}
          nfs:
            server: {{ required "An backup NFS server is required" .Values.global.backupArchive.nfsServer | quote }}
            path: {{ if .Values.global.backupArchive.nfsPath }}{{ .Values.global.backupArchive.nfsPath | quote }}{{ else }}{{ "/" }}{{ end }}
    {{- end }}
  {{- end }}
      restartPolicy: Always
{{- end }}
{{- end }}
