{{- if or (or (eq "all" .Values.global.deploymentType) (eq "internal" .Values.global.deploymentType) ) (not .Values.global.deploymentType)}}
{{- if not .Values.global.secretsService }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-finalize
type: Opaque
data:
  dbPassword: {{ include "dbPassFinalize" . | b64enc }}
  dbUser: {{ include "dbUserFinalize" . | b64enc }}
  mqPassword: {{ include "mqPassFinalize" . | b64enc }}
  mqUser: {{ include "mqUserFinalize" . | b64enc }}
{{- end }}
{{- if not .Values.global.pkiService }}
---
{{- $finalize := .Files.Glob "files/finalize*" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-finalize-certs
data:
{{ ( .Files.Glob "files/ca.crt" ).AsSecrets | trim | indent 2 }}
{{ ( $finalize ).AsSecrets | indent 2 }}
{{- end }}
{{- end }}
