{{- if or (or (eq "all" .Values.global.deploymentType) (eq "external" .Values.global.deploymentType) )  (not  .Values.global.deploymentType) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "sda.fullname" . }}-inbox
  labels:
    app: {{ template "sda.fullname" . }}-inbox
spec:
  ports:
  - name: 
    port: {{ ternary 2222 443 ( empty .Values.global.inbox.s3Url ) }}
    targetPort: inbox
    protocol: TCP
  selector:
    app: {{ template "sda.fullname" . }}-inbox
{{- end }}
