{{- if or (or (eq "all" .Values.global.deploymentType) (eq "internal" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sda.fullname" . }}-ingest
  labels:
    role: ingest
    app: {{ template "sda.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Release.Name }}-ingest
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{ .Values.global.networkPolicy.databaseNamespace }}: allowtraffic
    {{ .Values.global.networkPolicy.brokerNamespace }}: allowtraffic
spec:
  replicas: 1
  revisionHistoryLimit: {{ default "3" .Values.global.revisionHistory }}
  selector:
    matchLabels:
      app: {{ template "sda.name" . }}-ingest
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "sda.name" . }}-ingest
        role: ingest
        release: {{ .Release.Name }}
        {{ .Values.global.networkPolicy.databaseNamespace }}: allowtraffic
        {{ .Values.global.networkPolicy.brokerNamespace }}: allowtraffic
      annotations:
        {{- if not .Values.global.secretsService }}
        checksum/secret: {{ include (print $.Template.BasePath "/shared-secrets.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/ingest-secrets.yaml") . | sha256sum }}
        {{- end }}
{{- if .Values.global.podAnnotations }}
{{- toYaml .Values.global.podAnnotations | nindent 8 -}}
{{- end }}
{{- if .Values.ingest.annotations }}
{{- toYaml .Values.ingest.annotations | nindent 8 -}}
{{- end }}
    spec:
    {{- if .Values.global.rbacEnabled}}
      serviceAccountName: {{ .Release.Name }}
    {{- end }}
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
    {{- if .Values.global.pkiPermissions }}
      initContainers:
      - name: tls-init
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["/bin/cp /tls-certs/* /tls/ && chown 65534:65534 /tls/* && chmod 0600 /tls/*"]
        securityContext:
          allowPrivilegeEscalation: false
{{- if .Values.global.extraSecurityContext }}
{{- toYaml .Values.global.extraSecurityContext | nindent 10 -}}
{{- end }}
        volumeMounts:
        - name: tls-certs
          mountPath: /tls-certs
        - name: tls
          mountPath: /tls
    {{- end }}
      containers:
      - name: ingest
        image: "{{ .Values.ingest.repository }}:{{ .Values.ingest.imageTag }}"
        imagePullPolicy: {{ .Values.ingest.imagePullPolicy | quote }}
        command: ["sda-ingest"]
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: ARCHIVE_TYPE
      {{- if eq "s3" .Values.global.archive.storageType }}
          value: "s3"
        - name: ARCHIVE_URL
          value: {{ required "S3 archive URL missing" .Values.global.archive.s3Url }}
        - name: ARCHIVE_BUCKET
          value: {{ required "S3 archive bucket missing" .Values.global.archive.s3Bucket }}
        - name: ARCHIVE_REGION
          value: {{ default "us-east-1" .Values.global.archive.s3Region }}
        - name: ARCHIVE_CHUNKSIZE
          value: {{ .Values.global.archive.s3ChunkSize | quote }}
      {{- if .Values.global.archive.s3CaFile }}
        - name: ARCHIVE_CACERT
          value: {{ template "tlsPath" . }}/{{ .Values.global.archive.s3CaFile }}
      {{- end }}
      {{- else }}
          value: "posix"
        - name: ARCHIVE_LOCATION
          value: "{{ .Values.global.archive.volumePath }}/%s"
      {{- end }}
      {{- if .Values.global.broker.ssl }}
        - name: BROKER_CACERT
          value: {{ include "tlsPath" . }}/ca.crt
        {{- if .Values.global.broker.verifyPeer }}
        - name: BROKER_CLIENTCERT
          value: {{ include "tlsPath" . }}/ingest.crt
        - name: BROKER_CLIENTKEY
          value: {{ include "tlsPath" . }}/ingest.key
        {{- end }}
      {{- end }}
        - name: BROKER_DURABLE
          value: {{ .Values.global.broker.durable | quote }}
        - name: BROKER_EXCHANGE
          value: {{ default "lega" .Values.global.broker.exchange }}
        - name: BROKER_QUEUE
          value: "files"
        - name: BROKER_HOST
          value: {{ required "A valid MQ host is required" .Values.global.broker.host | quote }}
        - name: BROKER_PORT
          value: {{ .Values.global.broker.port | quote }}
        - name: BROKER_ROUTINGERROR
          value: {{ .Values.global.broker.routingError }}
        - name: BROKER_ROUTINGKEY
          value: "archived"
        - name: BROKER_VHOST
          value: {{ .Values.global.broker.vhost | quote }}
        - name: BROKER_SERVERNAME
          value: {{ .Values.global.broker.host | quote }}
        - name: BROKER_SSL
          value: "true"
        - name: BROKER_VERIFYPEER
          value: {{ .Values.global.broker.verifyPeer | quote }}
        - name: C4GH_FILEPATH
          value: {{ template "c4ghPath" . }}/{{ default "c4gh.sec.pem" .Values.global.c4gh.file }}
      {{- if or (eq "verify-ca" .Values.global.db.sslMode) (eq "verify-full" .Values.global.db.sslMode) }}
        - name: DB_CACERT
          value: {{ include "tlsPath" . }}/ca.crt
      {{- end }}
      {{- if eq "verify-full" .Values.global.db.sslMode }}
        - name: DB_CLIENTCERT
          value: {{ include "tlsPath" . }}/ingest.crt
        - name: DB_CLIENTKEY
          value: {{ include "tlsPath" . }}/ingest.key
      {{- end }}
        - name: DB_DATABASE
          value: {{ default "lega" .Values.global.db.name | quote }}
        - name: DB_HOST
          value: {{ required "A valid DB host is required" .Values.global.db.host | quote }}
        - name: DB_PORT
          value: {{ .Values.global.db.port | quote }}
        - name: DB_SSLMODE
          value: {{ .Values.global.db.sslMode | quote }}
        - name: INBOX_TYPE
      {{- if eq "s3" .Values.global.inbox.storageType }}
          value: "s3"
        - name: INBOX_BUCKET
          value: {{ required "S3 inbox bucket missing" .Values.global.inbox.s3Bucket }}
      {{- if .Values.global.inbox.s3CaFile }}
        - name: INBOX_CACERT
          value: {{ template "tlsPath" . }}/{{ .Values.global.inbox.s3CaFile }}
      {{- end }}
        - name: INBOX_REGION
          value: {{ default "us-east-1" .Values.global.inbox.s3Region }}
        - name: INBOX_URL
          value: {{ required "S3 inbox URL missing" .Values.global.inbox.s3Url }}
      {{- else }}
          value: "posix"
        - name: INBOX_LOCATION
          value: "{{ .Values.global.inbox.path }}/%s"
      {{- end }}
      {{- if .Values.global.logLevel }}
        - name: LOG_LEVEL
          value: {{ .Values.global.logLevel | quote }}
      {{- end }}
      {{- if not .Values.global.secretsService }}
      {{- if eq "s3" .Values.global.archive.storageType }}
        - name: ARCHIVE_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-s3archive-keys
              key: s3ArchiveAccessKey
        - name: ARCHIVE_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-s3archive-keys
              key: s3ArchiveSecretKey
      {{- end }}
        - name: BROKER_PASSWORD
          valueFrom:
              secretKeyRef:
                name: {{ template "sda.fullname" . }}-ingest
                key: mqPassword
        - name: BROKER_USER
          valueFrom:
              secretKeyRef:
                name: {{ template "sda.fullname" . }}-ingest
                key: mqUser
        - name: DB_PASSWORD
          valueFrom:
              secretKeyRef:
                name: {{ template "sda.fullname" . }}-ingest
                key: dbPassword
        - name: DB_USER
          valueFrom:
              secretKeyRef:
                name: {{ template "sda.fullname" . }}-ingest
                key: dbUser
        - name: C4GH_PASSPHRASE
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-ingest
              key: c4ghPassphrase
      {{- if eq "s3" .Values.global.inbox.storageType }}
        - name: INBOX_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-s3inbox-keys
              key: s3InboxAccessKey
        - name: INBOX_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-s3inbox-keys
              key: s3InboxSecretKey
      {{- end }}
      {{- end }}
        resources:
{{ toYaml .Values.ingest.resources | trim | indent 10 }}
        volumeMounts:
      {{- if not .Values.global.secretsService }}
        - name: c4gh
          mountPath: {{ template "c4ghPath" . }}
      {{- end }}
      {{- if not .Values.global.pkiService }}
        - name: tls
          mountPath: "{{ template "tlsPath" . }}"
      {{- end }}
      {{- if eq "posix" .Values.global.archive.storageType }}
        - name: archive
          mountPath: {{ .Values.global.archive.volumePath | quote }}
      {{- end }}
      {{- if eq "posix" .Values.global.inbox.storageType }}
        - name: inbox
          mountPath: {{ .Values.global.inbox.path | quote }}
      {{- end }}
      volumes:
    {{- if not .Values.global.secretsService }}
        - name: c4gh
          secret:
            defaultMode: 0440
            secretName: {{ template "sda.fullname" . }}-c4gh
            items:
            - key: {{ .Values.global.c4gh.file }}
              path: {{ .Values.global.c4gh.file }}
      {{- end }}
    {{- if not .Values.global.pkiService }}
        - name: {{ ternary "tls" "tls-certs" (empty .Values.global.pkiPermissions) }}
          secret:
            defaultMode: 0440
            secretName: {{ template "sda.fullname" . }}-ingest-certs
      {{- if .Values.global.pkiPermissions }}
        - name: tls
          emptyDir:
            medium: Memory
            sizeLimit: 10Mi
      {{- end }}
    {{- end }}
      {{- if eq "posix" .Values.global.archive.storageType }}
        - name: archive
        {{- if .Values.global.archive.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.global.archive.existingClaim }}
        {{- else }}
          nfs:
            server: {{ required "An archive NFS server is required" .Values.global.archive.nfsServer | quote }}
            path: {{ if .Values.global.archive.nfsPath }}{{ .Values.global.archive.nfsPath | quote }}{{ else }}{{ "/" }}{{ end }}
        {{- end }}
      {{- end }}
      {{- if eq "posix" .Values.global.inbox.storageType }}
        - name: inbox
        {{- if .Values.global.inbox.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.global.inbox.existingClaim }}
        {{- else }}
          nfs:
            server: {{ required "An inbox NFS server is required" .Values.global.inbox.nfsServer | quote }}
            path: {{ if .Values.global.inbox.nfsPath }}{{ .Values.global.inbox.nfsPath | quote }}{{ else }}{{ "/" }}{{ end }}
        {{- end }}
      {{- end }}
      restartPolicy: Always
{{- end }}
