{{- if or (or (eq "all" .Values.global.deploymentType) (eq "external" .Values.global.deploymentType) )  (not  .Values.global.deploymentType) }}
{{- if eq "S3Storage" .Values.global.inbox.storageType }}
{{- if not .Values.global.confFile }}
{{- $jwtPub := .Files.Glob (printf "files/%s" .Values.global.elixir.pubKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-inbox
type: Opaque
data:
{{- if $jwtPub }}
{{ ( $jwtPub ).AsSecrets | indent 2 }}
{{- end }}
  mqPassword: {{ include "mqPassInbox" . | b64enc }}
  s3InboxAccessKey: {{ .Values.global.inbox.s3AccessKey | b64enc }}
  s3InboxSecretKey: {{ .Values.global.inbox.s3SecretKey | b64enc }}
{{- end }}
{{- if not .Values.global.pkiService }}
---
{{- $s3inbox := .Files.Glob "files/inbox*" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-inbox-certs
data:
{{ ( .Files.Glob "files/ca.crt" ).AsSecrets | trim | indent 2 }}
{{ ( $s3inbox ).AsSecrets | indent 2 }}
{{- end }}
{{- end }}
{{- end }}
