{{- if or (or (eq "all" .Values.global.deploymentType) (eq "external" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
{{- if eq "FileStorage" .Values.global.inbox.storageType }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-inbox
type: Opaque
data:
  mqPassword: {{ include "mqPassInbox" . | b64enc }}
  cegaCredentials: {{ printf "%s:%s" .Values.global.cega.user .Values.global.cega.password | quote | trimall "\"" | b64enc }}
{{- if not .Values.global.pkiService }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-inbox-certs
data:
{{ ( .Files.Glob "files/cacerts" ).AsSecrets | trim | indent 2 }}
{{ ( .Files.Glob "files/inbox.p12" ).AsSecrets | indent 2 }}
{{- end }}
{{- end }}
{{- end }}
