name: Helm linter

on: [push]

jobs:
  lint_sda-db:
    name: Lint sda-db
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install helm3
      run: |
        wget https://get.helm.sh/helm-v3.1.2-linux-amd64.tar.gz -O - | tar -xz
        sudo cp linux-amd64/helm /usr/local/bin/helm
    - name: Lint sda-db
      run: |
        bash .github/ci_tests/lint_helper.sh sda-db
        helm lint sda-db

  lint_sda-mq:
    name: Lint sda-mq
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install helm3
      run: |
        wget https://get.helm.sh/helm-v3.1.2-linux-amd64.tar.gz -O - | tar -xz
        sudo cp linux-amd64/helm /usr/local/bin/helm
    - name: Lint sda-mq
      run: |
        bash .github/ci_tests/lint_helper.sh sda-mq
        helm lint sda-mq

  lint_sda-svc:
    name: Lint sda-svc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install helm3
      run: |
        wget https://get.helm.sh/helm-v3.1.2-linux-amd64.tar.gz -O - | tar -xz
        sudo cp linux-amd64/helm /usr/local/bin/helm
    - name: Lint sda-svc
      run: |
        bash .github/ci_tests/lint_helper.sh sda-svc
        helm lint sda-svc

  lint_sda-orch:
    name: Lint sda-orch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install helm3
      run: |
        wget https://get.helm.sh/helm-v3.1.2-linux-amd64.tar.gz -O - | tar -xz
        sudo cp linux-amd64/helm /usr/local/bin/helm
    - name: Lint sda-orch
      run: |
        bash .github/ci_tests/lint_helper.sh sda-orch
        helm lint sda-orch
